MODEL:
  TYPE: swinfc
  NAME: swin_base_patch4_window7_224
  DROP_PATH_RATE: 0.5

  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
LOSS:
  BRANCH_RATE: [0.4, 0.6, 0.8]
  ALPHA: 0.4